/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ProyectoJDBC;
import exceptions.MyException;
import javax.swing.JOptionPane;
import modelo.User;

/**
 *
 * @author MPort y SGamarra
 */
public class GestioUsuaris extends javax.swing.JDialog {

        private ProyectoJDBC proyectoJDBC;
        private User userSeleccionat;

    public User getUserSeleccionat() {
        return userSeleccionat;
    }

    public void setUserSeleccionat(User userSeleccionat) {
        this.userSeleccionat = userSeleccionat;
    }

    public ProyectoJDBC getProyectoJDBC() {
        return proyectoJDBC;
    }

    public void setProyectoJDBC(ProyectoJDBC proyectoJDBC) {
        this.proyectoJDBC = proyectoJDBC;
    }

    
    
    /**
     * Creates new form ListadoUsers
     */
    public GestioUsuaris(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        proyectoJDBC = new ProyectoJDBC();
//        users = proyectoJDBC.borraruser
        userSeleccionat = new User();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Usuari");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Esborrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // EDITAR USUARI
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Tens que seleccionar un usuari");
        } else {
            int respuesta = JOptionPane.showConfirmDialog(this, "Estás segur?", "CONFIRMA",
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    // creamos en PrendaJDBC la funcion borrarPrenda que la invocaremos aqui
                    proyectoJDBC.updateUser(userSeleccionat);
                    // llamamos a la funcion bajaprenda de ListaPrendas
                    JOptionPane.showMessageDialog(this, "Usuari modificat amb exit");
                    dispose();
                } catch (MyException ex) {
                    JOptionPane.showMessageDialog(this, "No s'ha pogut modificar l'usuari",
                            "ERROR: Usuari no modificat", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // ESBORRAR USUARI
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Tens que seleccionar un usuari");
        } else {
            int respuesta = JOptionPane.showConfirmDialog(this, "Estás segur?", "CONFIRMA",
                    JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                try {
                    // creamos en PrendaJDBC la funcion borrarPrenda que la invocaremos aqui
                    proyectoJDBC.borrarUser(userSeleccionat);
                    // llamamos a la funcion bajaprenda de ListaPrendas
                    JOptionPane.showMessageDialog(this, "Prenda borrada con exito");
                    dispose();
                } catch (MyException ex) {
                    JOptionPane.showMessageDialog(this, "No s'ha pogut esborrar l'usuari",
                            "ERROR: Usuari no esborrat", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
